# Generated by Django 4.0.2 on 2022-03-12 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unit',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='user',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='user',
            name='unit',
        ),
        migrations.AddField(
            model_name='user',
            name='balance',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='pending_balance',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(blank=True, choices=[('branch-lead', 'Branch Lead'), ('admin', 'Admin'), ('member', 'Member'), ('merchant', 'Merchant'), ('super-admin', 'Super Admin')], max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='Branch',
        ),
        migrations.DeleteModel(
            name='Unit',
        ),
    ]
